[default]
src = 'contracts'
out = 'artifacts/contracts'
libs = ['lib']
auto_detect_solc = false
solc_version = '0.8.9'
# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
# Fuzz more than the default 256
fuzz_runs = 1_000


# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000
